# Generated by Django 4.0.3 on 2022-05-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
                ('joined_date', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
    ]
